services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WebitDe\ShortcutStatuscodes\:
    resource: '../Classes/*'

  TYPO3\CMS\Core\Routing\PageArguments:
    autowire: false
  TYPO3\CMS\Core\Site\Entity\Site:
    autowire: false
  TYPO3\CMS\Core\Site\Entity\SiteLanguage:
    autowire: false
